import java.util.HashMap;

/**
 * Created by Rukshar Alam on 3/29/2018.
 */
public class PrintCode {

    HashMap<Character,String > map  = new HashMap<Character,String>();
    HuffmanNode huffmanNode ;

    public PrintCode(HuffmanNode huffmanNode){
        this.huffmanNode = huffmanNode;
    }

    // recursive function to print the
    // huffman-code through the tree traversal.
    // Here s is the huffman - code generated.

    private boolean checkLeaf(HuffmanNode root){
        //System.out.println("checking leaf");
        boolean leftCh = root.getLeft()
                == null;
        boolean rightCh = root.getRight()
                == null;
        char temp = root.getC();
        boolean letter =  temp>='a' && temp<='z';

        if (leftCh && rightCh && letter) {
            return true;
        }
        return false;
    }
    public  void printCode(HuffmanNode root, String s)
    {

        //System.out.println("lol");

        // base case; if the left and right are null
        // then its a leaf node and we print
        // the code s generated by traversing the tree.
        if (checkLeaf(root)) {

            // c is the character in the node
            //System.out.println(root.c + ":" + s);
            char temp = root.getC();
            map.put(temp, s);

            return;
        }

        // if we go to left then add "0" to the code.
        // if we go to the right add"1" to the code.

        // recursive calls for left and
        // right sub-tree of the generated tree.
        String leftSide = s + "0";
        printCode(root.getLeft(), leftSide);
        String rightSide = s + "1";
        printCode(root.getRight(), rightSide);
    }

    public void printMap(){
        System.out.println("in print map");
        printCode(huffmanNode," ");
        int size = map.size();
        for (HashMap.Entry<Character, String> entry : map.entrySet())
        {
            System.out.println(entry.getKey() + ":" + entry.getValue());
        }
    }


}
